# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: anime_food_development

# test:
#   <<: *default
#   database: anime_food_test

# production:
#   <<: *default
#   database: anime_food_production
#   username: anime_food
#   password: <%= ENV['ANIME_FOOD_DATABASE_PASSWORD'] %>

default: &default
  adapter: 'postgresql'
  host: containers-us-west-82.railway.app
  username: postgres
  password: 7R0GtPkZD8m7gH8FmyqX
  port: 7703

development:
  <<: *default
  database: railway

test:
  <<: *default  
  database: anime_food_test

production:
  <<: *default
  database: railway
